services:
  # Symfony Backend with PHP-FPM
  backend:
    build:
      context: ./monopoly-backend
      dockerfile: Dockerfile
    container_name: monopoly-backend
    ports:
      - "8000:8000"
    volumes:
      - ./monopoly-backend:/app
      - /app/vendor
    environment:
      - APP_ENV=dev
      - APP_SECRET=monopoly-secret-key-change-in-production
      - WEBSOCKET_HOST=0.0.0.0
      - WEBSOCKET_PORT=8080
    networks:
      - monopoly-network
    command: php -S 0.0.0.0:8000 -t public/

  # WebSocket Server (separate process)
  websocket:
    build:
      context: ./monopoly-backend
      dockerfile: Dockerfile
    container_name: monopoly-websocket
    ports:
      - "8080:8080"
    volumes:
      - ./monopoly-backend:/app
      - /app/vendor
    environment:
      - APP_ENV=dev
      - APP_SECRET=monopoly-secret-key-change-in-production
      - WEBSOCKET_HOST=0.0.0.0
      - WEBSOCKET_PORT=8080
    networks:
      - monopoly-network
    command: php bin/console websocket:start
    depends_on:
      - backend

  # Next.js Frontend
  frontend:
    build:
      context: ./monopoly-frontend
      dockerfile: Dockerfile
    container_name: monopoly-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./monopoly-frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_WS_URL=ws://localhost:8080
    networks:
      - monopoly-network
    depends_on:
      - backend
    command: npm run dev

networks:
  monopoly-network:
    driver: bridge

