[build]
builder = "nixpacks"

[deploy]
startCommand = "echo 'Use service-specific commands'"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

